dockerd:
  image: docker:dind
  privileged: true # required for the daemon only
  # links:
  #   - registry
agentd:
  build: .
  dockerfile: Dockerfile.agentd
  links:
    # - supervisord
    - dockerd
    # - registry
# supervisord:
#   build: .
#   dockerfile: Dockerfile.supervisord
#   links:
#     - registry
# registry:
#   image: distribution/registry
